version: '3.8'

services:
  consul:
    image: consul:1.15  # ✅ FIX: use a specific version
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./consul/config:/consul/config
    command: "consul agent -dev -client=0.0.0.0"

  service-a:
    build: ./service-a
    depends_on:
      - consul

  service-b:
    build: ./service-b
    depends_on:
      - consul

  service-c:
    build: ./service-c
    depends_on:
      - consul

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - consul
